FROM gaianmobius/openjdk-21-mvn-3.9.6:latest
COPY pom.xml /tmp/jio-test/pom.xml
COPY src /tmp/jio-test/src/
COPY .mvn /tmp/jio-test/.mvn/
WORKDIR /tmp/jio-test/
ENV CLASSPATH=/tmp/jio/jio-test/target/*