FROM gaianmobius/openjdk-21-mvn-3.9.6:latest
COPY pom.xml /tmp/jio-http/pom.xml
COPY src /tmp/jio-http/src/
COPY .mvn /tmp/jio-http/.mvn/
WORKDIR /tmp/jio-http/
ENV CLASSPATH=/tmp/jio/jio-http/target/*