FROM gaianmobius/openjdk-21-mvn-3.9.6:latest
COPY pom.xml /tmp/jio-jdbc/pom.xml
COPY src /tmp/jio-jdbc/src/
COPY .mvn /tmp/jio-jdbc/.mvn/
WORKDIR /tmp/jio-jdbc/
ENV CLASSPATH=/tmp/jio/jio-jdbc/target/*